[package]
name = "fanrf"
version = "0.1.0"
authors = ["Tyler Hall <tylerwhall@gmail.com>"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/tylerwhall/fanrf"

[dependencies]
bitflags = "0.7"
clap = "2.20"
env_logger = "0.3"
log = "0.3"
spidev = "0.3"
sysfs_gpio = "0.5.0"
